// Tiny boot layer: show real HTML first, then start the core app. Optional UI layers never block navigation.
(function(){
  const PROFILE='abacus-ai-profile-v2',LANG='abacus-ai-language',app=document.getElementById('app');
  if(!app)return;
  try{history.scrollRestoration='manual'}catch{}
  const resetScroll=()=>{window.scrollTo(0,0);document.documentElement.scrollTop=0;document.body.scrollTop=0};
  let scrollFrame=0;
  const scheduleResetScroll=()=>{if(scrollFrame)return;scrollFrame=requestAnimationFrame(()=>{scrollFrame=0;resetScroll()})};
  const scrollObserver=new MutationObserver(scheduleResetScroll);scrollObserver.observe(app,{childList:true,subtree:false});
  window.addEventListener('pageshow',resetScroll);
  const read=()=>{try{return JSON.parse(localStorage.getItem(PROFILE)||'null')}catch{return null}};
  const fail=()=>{app.innerHTML='<div class="screen onboarding center"><div style="max-width:520px;margin:auto"><div style="font-size:56px">🧮</div><h1>Babi is waking up…</h1><p>We could not start Abacus World.</p><button class="primary" type="button" onclick="location.reload()">Try Again</button></div></div>';resetScroll()};
  function voicePicker(){
    const card=document.querySelector('.ob-card');if(!card||document.getElementById('bootVoiceChoice'))return;
    const box=document.createElement('section');box.id='bootVoiceChoice';box.className='boot-voice-choice';box.innerHTML='<div class="boot-voice-title">🔊 How should Babi talk?</div><div class="boot-voice-sub">Pick English or Tamil • Tanglish.</div><div class="boot-voice-buttons"><button type="button" data-boot-lang="en">🇬🇧 English</button><button type="button" data-boot-lang="ta">🇮🇳 Tamil • Tanglish</button></div>';card.prepend(box);
    if(!document.getElementById('bootVoiceStyle')){const s=document.createElement('style');s.id='bootVoiceStyle';s.textContent='.boot-voice-choice{margin:0 0 15px;padding:14px;border-radius:19px;background:linear-gradient(135deg,#eef9ff,#fff4d8);border:2px solid rgba(82,206,247,.35);text-align:center}.boot-voice-title{font:950 17px ui-rounded,system-ui,sans-serif;color:#4b2c18}.boot-voice-sub{margin:5px 0 10px;font:700 12px/1.3 ui-rounded,system-ui,sans-serif;color:#725e50}.boot-voice-buttons{display:grid;grid-template-columns:1fr 1fr;gap:9px}.boot-voice-buttons button{min-height:48px;border:2px solid #d9c49d;border-radius:15px;background:#fff;font:900 15px ui-rounded,system-ui,sans-serif;color:#4b2c18}.boot-voice-buttons button.selected{border-color:#f1a52b;background:#fff1ca}';document.head.appendChild(s)}
    const current=localStorage.getItem(LANG)==='ta'?'ta':'en';const speak=lang=>{if(!('speechSynthesis' in window))return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(lang==='ta'?'ஹாய்! நான் Babi. இப்போ நாம Abacus கத்துக்கலாம்.':'Hey! I am Babi. Let’s learn Abacus together.');u.lang=lang==='ta'?'ta-IN':'en-IN';u.rate=lang==='ta'?1.08:1.12;u.pitch=1.08;speechSynthesis.speak(u)}catch{}};
    box.querySelectorAll('[data-boot-lang]').forEach(b=>b.onclick=()=>{localStorage.setItem(LANG,b.dataset.bootLang);box.querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x===b));speak(b.dataset.bootLang)});box.querySelectorAll('button').forEach(b=>b.classList.toggle('selected',b.dataset.bootLang===current));
  }
  document.addEventListener('click',e=>{const button=e.target.closest?.('#lessonGo');if(!button)return;if(button.dataset.lessonAdvancing==='1'){e.stopImmediatePropagation();e.preventDefault();return}button.dataset.lessonAdvancing='1';requestAnimationFrame(()=>{button.disabled=true})},true);
  async function loadEnhancements(){try{await import('./babiVoice.js');await import('./audioFx.js');await import('./kidUi.js');await import('./sessionSummary.js');await import('./homeBabi.js');await import('./learnPracticeUX.js');await import('./abacusInteractionUX.js');await import('./lessonStateMachine.js');await import('./practiceEntryUX.js');await import('./v1ProgressUX.js');await import('./parentProgressUX.js')}catch(err){console.error('Optional layer failed',err)}}
  async function startApp(){try{await import('./challengeApp.js');resetScroll();if('requestIdleCallback' in window)requestIdleCallback(loadEnhancements,{timeout:2500});else setTimeout(loadEnhancements,1200)}catch(err){console.error('Core app failed to start',err);fail()}}
  const profile=read();
  if(profile){app.innerHTML='<div class="screen onboarding center"><div style="margin:auto"><div style="font-size:52px">🧮</div><h1>Babi is waking up…</h1></div></div>';startApp()}else{voicePicker();let age='',exp='',busy=false;const next=document.getElementById('obNext'),name=document.getElementById('childName');if(!next||!name)return;const ages=[...document.querySelectorAll('[data-age]')],exps=[...document.querySelectorAll('[data-exp]')],ready=()=>{next.disabled=!(name.value.trim()&&age&&exp)};ages.forEach(b=>b.onclick=()=>{age=b.dataset.age;ages.forEach(x=>x.classList.toggle('selected',x===b));ready()});exps.forEach(b=>b.onclick=()=>{exp=b.dataset.exp;exps.forEach(x=>x.classList.toggle('selected',x===b));ready()});name.oninput=ready;next.onclick=async()=>{if(busy||next.disabled)return;busy=true;next.disabled=true;const p={name:name.value.trim(),age,experience:exp,createdAt:Date.now()};try{localStorage.setItem(PROFILE,JSON.stringify(p))}catch{busy=false;next.disabled=false;return}if(exp==='known'){await import('./challengeApp.js').catch(fail);return}startApp()}}
  window.addEventListener('load',()=>{if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js?v=20260917-v56').catch(()=>{})});
})();
