// Universal child encouragement layer — short, English-only success applause.
(function(){
  const style=document.createElement('style');
  style.textContent=`.babi-correct-celebration{position:relative;display:flex;align-items:center;justify-content:center;gap:10px;margin:12px auto;padding:10px 16px;max-width:420px;border:3px solid #72c979;border-radius:20px;background:linear-gradient(135deg,#efffe9,#dff7d8);color:#176b2c;box-shadow:0 7px 18px rgba(40,110,50,.14);animation:babiCorrectIn .3s cubic-bezier(.2,.9,.3,1)}.babi-correct-celebration .babi-mini{width:52px;height:52px;flex:0 0 52px;animation:babiCorrectDance .75s ease-in-out 1}.babi-correct-celebration strong{display:block;font-size:20px;line-height:1.15}.babi-confetti{position:absolute;inset:0;pointer-events:none;overflow:hidden;border-radius:18px}.babi-confetti i{position:absolute;width:7px;height:13px;border-radius:3px;animation:babiConfetti .8s ease-out forwards}.babi-confetti i:nth-child(1){left:12%;top:35%}.babi-confetti i:nth-child(2){left:28%;top:10%;animation-delay:.05s}.babi-confetti i:nth-child(3){left:67%;top:12%;animation-delay:.1s}.babi-confetti i:nth-child(4){left:84%;top:35%;animation-delay:.15s}.babi-confetti i:nth-child(5){left:52%;top:5%;animation-delay:.2s}@keyframes babiCorrectIn{from{opacity:0;transform:translateY(7px) scale(.97)}to{opacity:1;transform:none}}@keyframes babiCorrectDance{0%,100%{transform:translateY(0) rotate(0) scale(1)}25%{transform:translateY(-8px) rotate(-6deg) scale(1.04)}50%{transform:translateY(0) rotate(6deg)}75%{transform:translateY(-5px) rotate(-4deg)}}@keyframes babiConfetti{0%{opacity:0;transform:translateY(0) rotate(0)}20%{opacity:1}100%{opacity:0;transform:translateY(-24px) rotate(150deg)}}`;
  document.head.appendChild(style);
  let lastKey='';
  const phrases=['Good job! 👏','Awesome! 🌟','Well done! 🎉','Great! ⭐','Nice! 👏'];let phraseIndex=0;
  function speakShort(text){try{if(!('speechSynthesis' in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(String(text).replace(/[^A-Za-z!?.,' ]/g,'').trim());u.lang='en-IN';u.rate=.9;u.pitch=1.2;u.volume=1;speechSynthesis.speak(u)}catch(e){}}
  function success(message,key){const host=document.querySelector('.lesson-card,.assessment,.content')||document.querySelector('#app');if(!host)return;const safeKey=String(key||message||host.textContent||'').slice(0,300);if(safeKey===lastKey)return;lastKey=safeKey;host.querySelector('.babi-correct-celebration')?.remove();const msg=message||phrases[phraseIndex++%phrases.length];const box=document.createElement('div');box.className='babi-correct-celebration';box.setAttribute('role','status');box.innerHTML=`<svg class="babi-mini babi" viewBox="0 0 160 160" aria-label="Babi celebrating"><use href="./assets/mascot/babi.svg#celebrate"></use></svg><strong>${msg}</strong><div class="babi-confetti"><i></i><i></i><i></i><i></i><i></i></div>`;const anchor=host.querySelector('.actions,.answer-card,.lesson-target,.lesson-current')||host.firstElementChild;if(anchor?.parentNode)anchor.parentNode.insertBefore(box,anchor.nextSibling);else host.appendChild(box);document.querySelectorAll('.babi,.babi-component').forEach(el=>{el.classList.remove('babi-buddy-dance','babi-celebrate');void el.offsetWidth;el.classList.add('babi-buddy-dance','babi-celebrate')});speakShort(msg);window.abacusSound?.correct?.();setTimeout(()=>box.remove(),1800)}
  function resultCelebration(){const title=document.querySelector('.result-title.coral'),problem=document.querySelector('.result-problem');if(title&&problem)success(null,`result:${problem.textContent}`)}
  function builderCelebration(){const h=document.querySelector('.lesson-card h1');if(!h)return;const m=h.textContent.match(/Make\s+(\d+)/i),n=Number(document.querySelector('.answer-card strong')?.textContent||NaN);if(m&&Number.isFinite(n)&&n===Number(m[1]))success(null,`builder:${m[1]}`)}
  function scan(){resultCelebration();builderCelebration()}
  window.BabiCelebration={success,scan};
  document.addEventListener('click',e=>{const el=e.target?.closest?.('#check,#builderCheck');if(el)setTimeout(scan,80)},true);
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',scan);else scan();
  new MutationObserver(()=>scan()).observe(document.body,{childList:true,subtree:true});
})();
