import {createAbacus,valueOf,generateProblem,getNextLevel,setValue} from './abacusEngine.js';

const KEY='abacus-ai-progress-v1';
const app=document.querySelector('#app');
let state=load();
let problem=null;
let childAbacus=createAbacus();
let wrongCount=0;

function freshState(){return {currentLevel:1,levels:{},rules:{direct:{correct:0,wrong:0},small:{correct:0,wrong:0},big:{correct:0,wrong:0},mixed:{correct:0,wrong:0}},streak:0};}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||freshState();}catch{return freshState();}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function nav(screen){render(screen);}

function babi(expression='idle',size='large'){return `<svg class="babi babi-${size} babi-${expression}" viewBox="0 0 160 160" aria-label="Babi the abacus bead"><use href="./assets/mascot/babi.svg#${expression}"></use></svg>`;}
function brand(){return `<div class="brand"><span class="brand-mark">🧮</span><span><strong>Abacus AI</strong><small>For Kids</small></span></div>`;}
function footer(){return `<div class="footer">Powered by PromptStudioAI<br><small>promptstudioai.in</small></div>`;}
function shell(content,options={}){const back=options.back?`<button class="icon-btn" id="back" aria-label="Back">←</button>`:'';app.innerHTML=`<div class="screen"><header class="topbar">${back}${brand()}<div class="top-actions"><span class="streak">★ ${state.streak}</span></div></header><main class="content">${content}</main>${footer()}</div>`;if(options.back)document.querySelector('#back').onclick=()=>nav(options.back);}
function render(screen='home'){if(screen==='welcome')return welcome();if(screen==='levels')return levels();if(screen==='practice')return practice();if(screen==='correct')return result(true);if(screen==='wrong')return result(false);if(screen==='levelup')return levelup();if(screen==='wall')return wall();return home();}

function welcome(){app.innerHTML=`<div class="screen welcome-screen"><div class="welcome-skip">Skip →</div><div class="welcome-brand">Abacus AI<span>For Kids</span></div><p class="tagline">Small beads. Big brains.</p>${babi('idle','hero')}<div class="speech"><strong>Hi!</strong><br>I'm Babi!<br>Let's make math fun!</div><button class="primary welcome-start" id="start">Let's Start <span>→</span></button>${footer()}</div>`;document.querySelector('#start').onclick=()=>nav('home');}

function home(){shell(`<section class="home-hero">${babi('idle','medium')}<h1>Hi There!</h1><p>Ready to move some beads?</p></section><div class="home-menu"><button class="menu-btn" id="play"><span class="menu-icon">▶</span><span><strong>Continue Learning</strong><small>Level ${state.currentLevel}</small></span><b>›</b></button><button class="menu-btn" id="levels"><span class="menu-icon">▦</span><span><strong>Level Map</strong><small>See your progress</small></span><b>›</b></button><button class="menu-btn" id="practice"><span class="menu-icon">◎</span><span><strong>Practice</strong><small>Play and get better</small></span><b>›</b></button><button class="menu-btn placeholder" disabled><span class="menu-icon">★</span><span><strong>Achievements</strong><small>Coming Soon</small></span><em>V2</em></button><button class="menu-btn placeholder" disabled><span class="menu-icon">⚙</span><span><strong>Settings</strong><small>Coming Soon</small></span><em>V2</em></button></div>`,{});document.querySelector('#play').onclick=()=>startLevel(Math.min(state.currentLevel,6));document.querySelector('#levels').onclick=()=>nav('levels');document.querySelector('#practice').onclick=()=>startLevel(Math.min(state.currentLevel,6));}

function levels(){const items=Array.from({length:15},(_,i)=>{const n=i+1,locked=n>6,completed=Boolean(state.levels[n]?.completed);return `<button class="level ${locked?'locked':''} ${n===state.currentLevel?'current':''}" data-level="${n}" ${locked?'disabled':''}><span>${locked?'🔒':completed?'✓':'★'}</span><strong>${n}</strong></button>`;}).join('');shell(`<section class="map-intro">${babi('idle','small')}<div><h1>Level Map</h1><p>Learn step by step.<br>Build your abacus skills!</p></div></section><div class="levels">${items}</div><div class="map-note">More adventures coming soon!<strong>Levels 7 – 15</strong></div><p class="quote">“Every expert was once a beginner!”<br>— Babi</p>`,{back:'home'});document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>startLevel(Number(b.dataset.level)));}

function startLevel(level){if(level>6)return nav('wall');state.currentLevel=level;wrongCount=0;problem=generateProblem(level);childAbacus=createAbacus();save();render('practice');}

function abacusHtml(abacus=childAbacus,highlight=''){const rods=[1,0].map(rodIndex=>{const rod=abacus.rods[rodIndex];const lower=[0,1,2,3].map(i=>`<button class="bead lower ${i<rod.lower?'active':''} ${highlight==='lower'&&i<rod.lower?'tutor-pulse':''}" data-lower="${rodIndex}" data-index="${i}" aria-label="${i<rod.lower?'Active':'Inactive'} lower bead">${i<rod.lower?'●':'○'}</button>`).join('');return `<div class="rod-column ${highlight===`rod-${rodIndex}`?'tutor-rod':''}"><span class="rod-label">${rodIndex===0?'ONES':'TENS'}</span><div class="upper-zone"><button class="bead upper ${rod.upper?'active':''}" data-upper="${rodIndex}" aria-label="Upper bead">●</button></div><div class="beam"></div><div class="lower-zone">${lower}</div></div>`;}).join('');return `<div class="abacus-wrap"><div class="abacus"><div class="abacus-inner">${rods}</div></div></div>`;}

function practice(){const op=problem.operation==='add'?'+':'−';shell(`<div class="practice-meta"><span>Level ${state.currentLevel}</span><span>${state.streak}/3</span></div><div class="problem">${problem.operands[0]} ${op} ${problem.operands[1]} <span>= ?</span></div><p class="hint">Move the beads to make your answer.</p>${abacusHtml()}<div class="answer-card"><small>Your number</small><strong>${valueOf(childAbacus)}</strong></div><div class="actions"><button class="primary" id="check">Check <span>✓</span></button><button class="secondary" id="hint">💡 Tutor hint</button></div>`,{back:'home'});document.querySelectorAll('[data-upper]').forEach(b=>b.onclick=()=>{const r=Number(b.dataset.upper);childAbacus.rods[r].upper=!childAbacus.rods[r].upper;render('practice');});document.querySelectorAll('[data-lower]').forEach(b=>b.onclick=()=>{const r=Number(b.dataset.lower),i=Number(b.dataset.index),current=childAbacus.rods[r].lower;childAbacus.rods[r].lower=i<current?i:Math.min(4,i+1);render('practice');});document.querySelector('#check').onclick=check;document.querySelector('#hint').onclick=()=>showGuidedTutor();}

function tutorAbacus(value,highlight=''){const demo=createAbacus();setValue(demo,value);return abacusHtml(demo,highlight).replace(/data-lower="\d"/g,'').replace(/data-upper="\d"/g,'').replace(/<button class="bead/g,'<div class="bead').replace(/<\/button>/g,'</div>');}
function tutorStepContent(step){const a=problem.operands[0],b=problem.operands[1],answer=problem.answer;const op=problem.operation==='add'?'+':'−';if(step===0)return {title:'Find the ONES',text:`Let’s start with ${a}. Look at the ONES rod.`,value:a,highlight:'rod-0',button:'Show me →'};if(step===1)return {title:`Make ${a}`,text:`Babi shows ${a} beads. Watch how they move!`,value:a,highlight:'lower',button:`Now add ${b} →`};if(step===2)return {title:`Add ${b} more`,text:`Move ${b} more beads. You can do it!`,value:answer,highlight:'lower',button:'I’m ready!'};return {title:'Your turn! 🌟',text:`Now try ${a} ${op} ${b} on your own. Babi believes in you!`,value:0,highlight:'',button:'Let me try!'};}
function showGuidedTutor(){let step=0;const draw=()=>{const s=tutorStepContent(step);document.querySelector('#tutor-overlay')?.remove();const demo=s.value===0?'':tutorAbacus(s.value,s.highlight);const overlay=document.createElement('div');overlay.id='tutor-overlay';overlay.className='tutor-overlay';overlay.innerHTML=`<div class="tutor-card" role="dialog" aria-label="Babi Tutor"><button class="tutor-close" id="tutor-close" aria-label="Close tutor">×</button><div class="tutor-head">${babi(step>=3?'happy':'encourage','small')}<div><strong>Babi's Tutor</strong><small>Step ${Math.min(step+1,4)} of 4</small></div></div><h2>${s.title}</h2><p>${s.text}</p>${demo}<div class="tutor-dots">${[0,1,2,3].map(i=>`<span class="${i===step?'on':''}"></span>`).join('')}</div><button class="primary tutor-next" id="tutor-next">${s.button}</button></div>`;document.body.appendChild(overlay);document.querySelector('#tutor-close').onclick=()=>overlay.remove();document.querySelector('#tutor-next').onclick=()=>{if(step<3){step++;draw();}else overlay.remove();};};draw();}

function check(){const n=valueOf(childAbacus),correct=n===problem.answer,rule=problem.expectedRule;state.rules[rule]??={correct:0,wrong:0};state.levels[state.currentLevel]??={correct:0,wrong:0,completed:false};if(correct){state.rules[rule].correct++;state.streak++;wrongCount=0;state.levels[state.currentLevel].correct++;if(state.streak>=3){state.levels[state.currentLevel].completed=true;const finished=state.currentLevel;state.currentLevel=getNextLevel(finished,state.streak,0);save();if(finished>=6)return nav('wall');return nav('levelup');}save();return nav('correct');}state.rules[rule].wrong++;wrongCount++;state.streak=0;state.levels[state.currentLevel].wrong++;if(wrongCount>=2&&state.currentLevel>1)state.currentLevel=getNextLevel(state.currentLevel,0,wrongCount);save();nav('wrong');}

function result(correct){const op=problem.operation==='add'?'+':'−';shell(`${babi(correct?'happy':'encourage','large')}<h1 class="result-title ${correct?'coral':''}">${correct?'Great Job!':'Almost there!'}</h1><p class="result-sub">${correct?`That's correct! Streak ${state.streak}/3`:`Let's try again. You can do it!`}</p><div class="result-problem">${problem.operands[0]} ${op} ${problem.operands[1]} = <span>${correct?problem.answer:'?'}</span></div><div class="actions"><button class="primary" id="next">${correct?'Next Question →':'Try Again'}</button>${!correct?'<button class="secondary" id="hint">💡 Tutor hint</button>':''}</div>`,{});document.querySelector('#next').onclick=()=>{problem=generateProblem(state.currentLevel);childAbacus=createAbacus();nav(state.currentLevel>6?'wall':'practice');};if(!correct)document.querySelector('#hint').onclick=showGuidedTutor;}

function levelup(){shell(`${babi('celebrate','large')}<h1 class="levelup-title">Level Up!</h1><p class="result-sub">Amazing! You completed Level ${state.currentLevel-1}.</p><div class="levelup-card">You're getting really good<br>with your abacus!</div><div class="center"><button class="primary" id="next">Continue to Level ${state.currentLevel} →</button></div>`,{});document.querySelector('#next').onclick=()=>startLevel(state.currentLevel);}
function wall(){shell(`${babi('celebrate','large')}<h1 class="result-title coral">Great Progress!</h1><p class="result-sub">You've completed the free levels!</p><div class="wall-card"><h2>More levels coming soon!</h2><strong>Levels 7 – 15</strong><p>✓ Bigger number challenges<br>✓ New friend techniques<br>✓ Become an Abacus Master!</p></div><button class="primary" id="home">Stay Tuned!</button>`,{});document.querySelector('#home').onclick=()=>nav('home');}

if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
render('welcome');
