import {createAbacus,valueOf,setValue,generateProblem,checkAnswer,getNextLevel} from './abacusEngine.js';

const PROFILE_KEY='abacus-ai-profile-v2';
const PROGRESS_KEY='abacus-ai-progress-v2';
const app=document.querySelector('#app');
let profile=load(PROFILE_KEY,null);
let state=load(PROGRESS_KEY,{currentLevel:1,streak:0,levels:{},rules:{direct:{correct:0,wrong:0},small:{correct:0,wrong:0},big:{correct:0,wrong:0},mixed:{correct:0,wrong:0}},sessions:0});
let problem=null; let childAbacus=createAbacus(); let wrongCount=0; let assessmentScore=0; let assessmentIndex=0; let lastCompletedLevel=0;
const $=s=>document.querySelector(s);
function load(k,f){try{const v=JSON.parse(localStorage.getItem(k));return v??f}catch{return f}}
function save(){try{localStorage.setItem(PROGRESS_KEY,JSON.stringify(state));return true}catch(err){console.error('Progress save failed',err);return false}}
function saveProfile(){try{localStorage.setItem(PROFILE_KEY,JSON.stringify(profile));return true}catch(err){console.error('Profile save failed',err);return false}}
function babi(expr='idle',size='medium'){return `<svg class="babi babi-${size} babi-${expr}" viewBox="0 0 160 160" aria-label="Babi"><use href="./assets/mascot/babi.svg#${expr}"></use></svg>`}
function footer(){return `<div class="footer">Powered by PromptStudioAI<br><small>promptstudioai.in</small></div>`}
function shell(content,back='world'){app.innerHTML=`<div class="screen world-screen"><header class="topbar">${back?`<button class="icon-btn" id="back">←</button>`:''}<div class="brand"><span class="brand-mark">🧮</span><span><strong>Abacus AI</strong><small>For Kids</small></span></div><div class="top-actions"><span class="streak">★ ${state.streak}</span></div></header><main class="content">${content}</main>${footer()}</div>`;if(back)$('#back').onclick=()=>render(back)}
function render(screen='world'){if(!profile)return onboarding();({world,learn,levels,games,practice,result,levelup,assessment:assessmentQuestion,parent,locked,settings}[screen]||world)()}
function onboarding(){app.innerHTML=`<div class="screen onboarding"><div class="ob-brand">🧮 <b>Abacus AI</b><small>My Abacus World</small></div>${babi('idle','hero')}<h1>Let's build your Abacus World!</h1><p class="ob-sub">Babi will learn how to help you.</p><div class="ob-card"><label>What's your name?</label><input id="childName" maxlength="18" autocomplete="off" placeholder="Your first name"><label>How old are you?</label><div class="age-grid"><button data-age="3-5">3–5</button><button data-age="6-8">6–8</button><button data-age="8-10">8–10</button><button data-age="10+">10+</button></div><label>Have you used an abacus before?</label><div class="experience"><button data-exp="new"><b>🌱 I'm new</b><small>Teach me from the beginning</small></button><button data-exp="known"><b>🚀 I know abacus</b><small>Give me a quick challenge</small></button></div><button class="primary" id="obNext" disabled>Enter My World →</button></div>${footer()}</div>`;let age='',exp='';document.querySelectorAll('[data-age]').forEach(b=>b.onclick=()=>{age=b.dataset.age;document.querySelectorAll('[data-age]').forEach(x=>x.classList.toggle('selected',x===b));ready()});document.querySelectorAll('[data-exp]').forEach(b=>b.onclick=()=>{exp=b.dataset.exp;document.querySelectorAll('[data-exp]').forEach(x=>x.classList.toggle('selected',x===b));ready()});$('#childName').oninput=ready;function ready(){$('#obNext').disabled=!($('#childName').value.trim()&&age&&exp)}$('#obNext').onclick=()=>{profile={name:$('#childName').value.trim(),age,experience:exp,createdAt:Date.now()};if(!saveProfile()){toast('Could not save your profile. Please try again.');return}if(exp==='known')startAssessment();else render('world')}}
function ageCopy(){if(profile.age==='3-5')return {title:'Tiny Explorer',sub:'Short, playful bead adventures'};if(profile.age==='8-10')return {title:'Abacus Challenger',sub:'Accuracy, speed and smart moves'};if(profile.age==='10+')return {title:'Abacus Master Track',sub:'Challenge yourself and beat your best'};return {title:'Abacus Adventurer',sub:'Learn → practise → play → master'}}
function world(){const c=ageCopy();shell(`<section class="world-hero"><div class="world-babi">${babi('happy','small')}</div><div><p class="eyebrow">WELCOME BACK</p><h1>Hi ${esc(profile.name)}! 👋</h1><p>${c.title} · ${c.sub}</p></div></section><section class="mission"><span>🎯 TODAY'S MISSION</span><b>${state.streak?`Keep your ${state.streak}★ streak alive!`:'Make your first 3 bead wins!'}</b><button id="missionBtn">Start →</button></section><div class="journey"><button id="learn" class="journey-card learn-card"><span>🌱</span><b>LEARN</b><small>Discover the abacus</small></button><button id="practice" class="journey-card practice-card"><span>🧮</span><b>PRACTISE</b><small>Build answers with beads</small></button><button id="games" class="journey-card play-card"><span>🎮</span><b>PLAY</b><small>Bead games & challenges</small></button><button id="levels" class="journey-card master-card"><span>🏆</span><b>MASTER</b><small>Levels 1–15</small></button></div><section class="future-row"><button class="future" id="test"><span>📝</span><b>TEST</b><small>Coming Soon</small></button><button class="future" id="exam"><span>🎓</span><b>EXAM</b><small>Coming Soon</small></button><button class="future" id="compete"><span>🏅</span><b>COMPETE</b><small>Coming Soon</small></button></section><div class="bottom-row"><button class="soft" id="brain">🤖 Babi Brain</button><button class="soft" id="parent">👨‍👩‍👧 Parent Zone</button><button class="soft" id="settings">⚙ Settings</button></div>`,null);$('#learn').onclick=()=>render('learn');$('#practice').onclick=()=>state.currentLevel>6?render('locked'):startLevel(state.currentLevel);$('#missionBtn').onclick=()=>state.currentLevel>6?render('locked'):startLevel(state.currentLevel);$('#games').onclick=()=>render('games');$('#levels').onclick=()=>render('levels');['test','exam','compete'].forEach(id=>$('#'+id).onclick=()=>render('locked'));$('#brain').onclick=()=>brain();$('#parent').onclick=()=>parentGate();$('#settings').onclick=()=>render('settings')}
function learn(){shell(`<div class="section-head">${babi('encourage','small')}<div><h1>Abacus Adventure</h1><p>Start from zero. Babi teaches one idea at a time.</p></div></div><div class="lesson-list"><button data-lesson="0"><b>1. Meet your abacus</b><small>Rods, beads and place value</small></button><button data-lesson="1"><b>2. Make 1, 2, 3, 4</b><small>Move lower beads</small></button><button data-lesson="2"><b>3. Meet the 5 bead</b><small>Your upper bead is worth five</small></button><button data-lesson="3"><b>4. Make 6, 7, 8, 9</b><small>Five plus lower beads</small></button><button data-lesson="4"><b>5. Try a tiny challenge</b><small>Build numbers without typing</small></button><button data-lesson="5"><b>6. Ready for Level 1 ⭐</b><small>Three wins unlock your next adventure</small></button></div>`, 'world');document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>lesson(Number(b.dataset.lesson)))}
function lesson(i){const lessons=[['Meet the abacus','This rod is ONES. Lower beads are 1 each.','Tap the lower beads and watch the number.'],['Make 1–4','Each lower bead is worth 1.','Try building 3.'],['Meet 5','The upper bead is worth 5.','Tap the upper bead to make 5.'],['Make 6–9','Five plus lower beads makes 6–9.','Try building 8.'],['Tiny challenge','Build the number Babi asks for.','No typing — just move beads!'],['Level 1','You are ready! Level 1 starts with direct addition.','Make the answer on the abacus.']];const [title,text,task]=lessons[i];shell(`${babi('happy','large')}<div class="lesson-card"><p class="eyebrow">ABACUS ADVENTURE · ${i+1}/6</p><h1>${title}</h1><p>${text}</p><strong>🎯 ${task}</strong>${i<5?`<div class="mini-number">${[3,5,8,8,4,0][i]}</div>`:''}<button class="primary" id="lessonGo">${i===5?'Start Level 1 ⭐':'I got it →'}</button></div>`,'learn');$('#lessonGo').onclick=()=>i===5?startLevel(1):lesson(i+1)}
function levels(){const items=Array.from({length:15},(_,i)=>{const n=i+1,locked=n>6,done=!!state.levels[n]?.completed;return `<button class="world-level ${locked?'locked':''} ${n===state.currentLevel?'current':''}" data-level="${n}" ${locked?'disabled':''}><span>${locked?'🔒':done?'✓':'★'}</span><b>Level ${n}</b><small>${levelName(n)}</small></button>`}).join('');shell(`<div class="section-head"><div><h1>Master Path</h1><p>15 levels. Six are free to master.</p></div></div><div class="world-levels">${items}</div><div class="premium-tease"><b>🔒 Levels 7–15 are waiting</b><small>Small friends · Big friends · Mixed mastery</small></div>`,'world');document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>startLevel(Number(b.dataset.level)))}
function levelName(n){if(n<=2)return 'Direct addition';if(n<=4)return 'Direct subtraction';if(n<=6)return 'Small friend addition';if(n<=8)return 'Small friend subtraction';if(n<=10)return 'Big friend addition';if(n<=12)return 'Big friend subtraction';return n===13?'Mixed direct + small':n===14?'Mixed small + big':'Full mixed mastery'}
function games(){shell(`<div class="section-head">${babi('happy','small')}<div><h1>Abacus Playroom 🎮</h1><p>Play with the same skills you learn.</p></div></div><div class="game-grid"><button id="builder"><span>🧱</span><b>Bead Builder</b><small>Build a number</small></button><button id="hunt"><span>🔎</span><b>Number Hunt</b><small>Spot the number</small></button><button id="speed"><span>⚡</span><b>Speed Challenge</b><small>Beat your best</small></button><button id="feed"><span>🍎</span><b>Feed Babi</b><small>Solve to feed Babi</small></button></div>`,'world');$('#builder').onclick=()=>builder();$('#hunt').onclick=()=>startLevel(Math.min(state.currentLevel,6));$('#speed').onclick=()=>startLevel(Math.min(Math.max(state.currentLevel,2),6));$('#feed').onclick=()=>startLevel(Math.min(state.currentLevel,6))}
function builder(){let target=Math.floor(Math.random()*9)+1;let a=createAbacus();const draw=()=>{shell(`${babi('encourage','small')}<div class="lesson-card"><p class="eyebrow">BEAD BUILDER</p><h1>Make ${target}</h1><p>Use the beads. No typing!</p>${abacusHtml(a)}<div class="answer-card"><small>Your number</small><strong>${valueOf(a)}</strong></div><button class="primary" id="builderCheck">Check →</button></div>`,'games');document.querySelectorAll('[data-upper]').forEach(b=>b.onclick=()=>{a.rods[+b.dataset.upper].upper=!a.rods[+b.dataset.upper].upper;draw()});document.querySelectorAll('[data-lower]').forEach(b=>b.onclick=()=>{const r=+b.dataset.lower,i=+b.dataset.index,c=a.rods[r].lower;a.rods[r].lower=i<c?i:Math.min(4,i+1);draw()});$('#builderCheck').onclick=()=>{if(valueOf(a)===target){state.streak++;save();render('world')}else{toast('Almost! Keep moving the beads 🌟')}}};draw()}
function startAssessment(){assessmentIndex=0;assessmentScore=0;wrongCount=0;assessmentQuestion()}
function assessmentQuestion(){if(assessmentIndex>=5){const start=assessmentScore>=4?5:assessmentScore>=2?3:1;state.currentLevel=start;state.streak=0;wrongCount=0;save();render('world');toast(`Great! Babi found your starting Level ${start}.`);return}const examples=[[2,3],[5,4],[3,4],[7,2],[6,3]];const [a,b]=examples[assessmentIndex];const ans=a+b;let astate=createAbacus();shell(`${babi('encourage','small')}<div class="assessment"><p class="eyebrow">QUICK ABACUS CHECK · ${assessmentIndex+1}/5</p><h1>${a} + ${b} = ?</h1><p>Build your answer on the abacus.</p>${abacusHtml(astate)}<div class="answer-card"><small>Your number</small><strong>${valueOf(astate)}</strong></div><button class="primary" id="assessCheck">Check →</button></div>`,null);document.querySelectorAll('[data-upper]').forEach(x=>x.onclick=()=>{astate.rods[+x.dataset.upper].upper=!astate.rods[+x.dataset.upper].upper;assessmentQuestionRedraw(astate)});document.querySelectorAll('[data-lower]').forEach(x=>x.onclick=()=>{const r=+x.dataset.lower,i=+x.dataset.index,c=astate.rods[r].lower;astate.rods[r].lower=i<c?i:Math.min(4,i+1);assessmentQuestionRedraw(astate)});$('#assessCheck').onclick=()=>{if(valueOf(astate)===ans)assessmentScore++;assessmentIndex++;assessmentQuestion()}}
function assessmentQuestionRedraw(astate){const q=$('.assessment');q.querySelector('.abacus-wrap').outerHTML=abacusHtml(astate);q.querySelector('.answer-card strong').textContent=valueOf(astate);q.querySelectorAll('[data-upper]').forEach(x=>x.onclick=()=>{astate.rods[+x.dataset.upper].upper=!astate.rods[+x.dataset.upper].upper;assessmentQuestionRedraw(astate)});q.querySelectorAll('[data-lower]').forEach(x=>x.onclick=()=>{const r=+x.dataset.lower,i=+x.dataset.index,c=astate.rods[r].lower;astate.rods[r].lower=i<c?i:Math.min(4,i+1);assessmentQuestionRedraw(astate)})}
function startLevel(level){if(level>6)return render('locked');state.currentLevel=level;state.streak=0;wrongCount=0;problem=generateProblem(level);childAbacus=createAbacus();save();render('practice')}
function practice(){const op=problem.operation==='add'?'+':'−';shell(`<div class="practice-meta"><span>LEVEL ${state.currentLevel} · ${levelName(state.currentLevel)}</span><span>${state.streak}/3 ⭐</span></div><div class="problem">${problem.operands[0]} ${op} ${problem.operands[1]} <span>= ?</span></div><p class="hint">Move the beads to make your answer.</p>${abacusHtml(childAbacus)}<div class="answer-card"><small>Your number</small><strong>${valueOf(childAbacus)}</strong></div><div class="actions"><button class="primary" id="check">Check ✓</button><button class="secondary" id="hint">💡 Babi Hint</button></div>`,'world');bindAbacus(childAbacus,()=>render('practice'));$('#check').onclick=check;$('#hint').onclick=()=>toast(`Think about the ${problem.expectedRule} move. Babi says you can do it!`)}
function bindAbacus(a,redraw){document.querySelectorAll('[data-upper]').forEach(b=>b.onclick=()=>{a.rods[+b.dataset.upper].upper=!a.rods[+b.dataset.upper].upper;redraw()});document.querySelectorAll('[data-lower]').forEach(b=>b.onclick=()=>{const r=+b.dataset.lower,i=+b.dataset.index,c=a.rods[r].lower;a.rods[r].lower=i<c?i:Math.min(4,i+1);redraw()})}
function check(){const {correct}=checkAnswer(problem,childAbacus);const rule=problem.expectedRule;state.rules[rule]??={correct:0,wrong:0};state.levels[state.currentLevel]??={correct:0,wrong:0,completed:false};if(correct){state.rules[rule].correct++;state.levels[state.currentLevel].correct++;state.streak++;wrongCount=0;if(state.streak>=3){lastCompletedLevel=state.currentLevel;state.levels[lastCompletedLevel].completed=true;state.currentLevel=getNextLevel(lastCompletedLevel,state.streak,0);state.streak=0;save();if(lastCompletedLevel>=6)return render('locked');return render('levelup')}save();return render('result')}state.rules[rule].wrong++;state.levels[state.currentLevel].wrong++;wrongCount++;state.streak=0;if(wrongCount>=2){if(state.currentLevel>1)state.currentLevel=getNextLevel(state.currentLevel,0,wrongCount);wrongCount=0}save();render('result')}
function result(){const correct=valueOf(childAbacus)===problem.answer;const op=problem.operation==='add'?'+':'−';shell(`${babi(correct?'happy':'encourage','large')}<h1 class="result-title ${correct?'coral':''}">${correct?'Great job! 🌟':'Not yet — Babi believes in you!'}</h1><p class="result-sub">${correct?`You made ${problem.answer}. Streak ${state.streak}/3.`:`The answer is ${problem.answer}. Try the beads again.`}</p><div class="result-problem">${problem.operands[0]} ${op} ${problem.operands[1]} = <span>${problem.answer}</span></div><div class="actions"><button class="primary" id="next">${correct?'Next →':'Try Again'}</button><button class="secondary" id="hint">💡 Babi Hint</button></div>`,'world');$('#next').onclick=()=>{problem=generateProblem(Math.min(state.currentLevel,6));childAbacus=createAbacus();render('practice')};$('#hint').onclick=()=>toast(`This one uses the ${problem.expectedRule} idea. Watch the beads, then try again.`)}
function levelup(){const finished=lastCompletedLevel||Math.max(1,state.currentLevel-1);shell(`${babi('celebrate','large')}<h1 class="levelup-title">Level Up! 🏆</h1><p class="result-sub">You mastered Level ${finished}!</p><div class="levelup-card"><b>${esc(profile.name)}</b>, your abacus brain is getting stronger.<br>Next adventure: Level ${state.currentLevel}.</div><div class="center"><button class="primary" id="continue">Continue →</button></div>`,'world');$('#continue').onclick=()=>startLevel(state.currentLevel)}
function locked(){shell(`${babi('celebrate','large')}<h1 class="result-title coral">More adventures are waiting! 🔒</h1><div class="wall-card"><h2>Test · Exam · Competition</h2><p>Coming Soon — your journey is being built for you.</p><strong>Levels 7–15</strong><p>Small friends · Big friends · Mixed mastery</p></div><button class="primary" id="stay">Back to My World</button>`,'world');$('#stay').onclick=()=>render('world')}
function brain(){shell(`${babi('happy','small')}<div class="brain-card"><p class="eyebrow">BABI BRAIN</p><h1>Ask Babi about abacus math</h1><p>Try: “How do I make 8?” or “What is 3 + 4?”</p><input id="brainInput" placeholder="Ask Babi…"><button class="primary" id="brainAsk">Ask Babi →</button><div id="brainReply" class="brain-reply">I only teach abacus and math. 🌟</div></div>`,'world');$('#brainAsk').onclick=()=>{const q=$('#brainInput').value.trim().toLowerCase();const nums=(q.match(/\d+/g)||[]).map(Number);let r='I can help with making numbers and simple abacus sums.';if(nums.length===1&&nums[0]>=0&&nums[0]<=99)r=`To make ${nums[0]}, use the 5 bead when needed, then the lower beads. Let's build it together!`;if(nums.length>=2&&(/\-|minus|subtract/.test(q))){const a=nums[0],b=nums[1];r=a>=b?`${a} − ${b} = ${a-b}. Build ${a}, then subtract ${b} on the abacus.`:`Let's build ${a} first, then check whether ${b} can be subtracted.`}else if(nums.length>=2&&(/\+|plus|add/.test(q))){const a=nums[0],b=nums[1];r=`${a} + ${b} = ${a+b}. Build ${a}, then add ${b} on the abacus.`}$('#brainReply').textContent=r}}
function parentGate(){const answer=prompt('Parent check: 8 + 7 = ?');if(answer==='15')render('parent');else toast('That area is for grown-ups 😊')}
function parent(){const total=Object.values(state.rules).reduce((s,r)=>s+r.correct+r.wrong,0);const correct=Object.values(state.rules).reduce((s,r)=>s+r.correct,0);const accuracy=total?Math.round(correct/total*100):0;shell(`<div class="parent-card"><p class="eyebrow">PARENT ZONE</p><h1>${esc(profile.name)}'s Progress</h1><div class="stats"><div><b>${state.currentLevel}</b><small>Current level</small></div><div><b>${accuracy}%</b><small>Accuracy</small></div><div><b>${state.streak}</b><small>Streak</small></div></div><h3>What Babi sees</h3><p>Direct: ${state.rules.direct.correct} correct · ${state.rules.direct.wrong} wrong</p><p>Small friend: ${state.rules.small.correct} correct · ${state.rules.small.wrong} wrong</p><p>Big friend: ${state.rules.big.correct} correct · ${state.rules.big.wrong} wrong</p><p class="parent-note">This is learning progress data, not a developmental or diagnostic assessment.</p></div>`,'world')}
function settings(){shell(`<div class="settings-card"><p class="eyebrow">SETTINGS</p><h1>My Abacus World</h1><p><b>${esc(profile.name)}</b> · age ${profile.age}</p><button class="secondary" id="reset">Start over with a new profile</button></div>`,'world');$('#reset').onclick=()=>{try{localStorage.removeItem(PROFILE_KEY);localStorage.removeItem(PROGRESS_KEY)}catch{}location.reload()}}
function abacusHtml(a){const rods=[0,1].map(r=>{const rod=a.rods[r];const lowers=[0,1,2,3].map(i=>`<button class="bead lower ${i<rod.lower?'active':''}" data-lower="${r}" data-index="${i}"></button>`).join('');return `<div class="rod-column"><span class="rod-label">${r?'TENS':'ONES'}</span><div class="upper-zone"><button class="bead upper ${rod.upper?'active':''}" data-upper="${r}"></button></div><div class="beam"></div><div class="lower-zone">${lowers}</div></div>`}).join('');return `<div class="abacus-wrap"><div class="abacus"><div class="abacus-inner">${rods}</div></div></div>`}
function esc(v){return String(v).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function toast(text){const old=$('.toast');old?.remove();const t=document.createElement('div');t.className='toast';t.textContent=text;document.body.appendChild(t);setTimeout(()=>t.remove(),2400)}
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();
