import {createAbacus,valueOf,generateProblem,checkAnswer,getNextLevel} from './abacusEngine.js';

const PROFILE_KEY='abacus-ai-profile-v2',PROGRESS_KEY='abacus-ai-progress-v2';
const app=document.querySelector('#app');
let profile=load(PROFILE_KEY,null);
let state=load(PROGRESS_KEY,{currentLevel:1,streak:0,levels:{},rules:{direct:{correct:0,wrong:0},small:{correct:0,wrong:0},big:{correct:0,wrong:0},mixed:{correct:0,wrong:0}},sessions:0});
let problem=null,childAbacus=createAbacus(),wrongCount=0,assessmentScore=0,assessmentIndex=0,lastCompletedLevel=0;
const $=s=>document.querySelector(s);
function load(k,f){try{const v=JSON.parse(localStorage.getItem(k));return v??f}catch{return f}}
function save(){try{localStorage.setItem(PROGRESS_KEY,JSON.stringify(state))}catch(e){console.error(e)}}
function saveProfile(){try{localStorage.setItem(PROFILE_KEY,JSON.stringify(profile));return true}catch{return false}}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function babi(expr='idle',size='medium'){return `<svg class="babi babi-${size} babi-${expr}" viewBox="0 0 160 160" aria-label="Babi"><use href="./assets/mascot/babi.svg#${expr}"></use></svg>`}
function footer(){return `<div class="footer">Powered by PromptStudioAI<br><small>promptstudioai.in</small></div>`}
function shell(content,back='world'){app.innerHTML=`<div class="screen world-screen"><header class="topbar">${back?'<button class="icon-btn" id="back" type="button">←</button>':''}<div class="brand"><span class="brand-mark">🧮</span><span><strong>Abacus AI</strong><small>For Kids</small></span></div><div class="top-actions"><span class="streak">★ ${state.streak}</span></div></header><main class="content">${content}</main>${footer()}</div>`;if(back)$('#back').onclick=()=>render(back);queueMicrotask(()=>window.dispatchEvent(new Event('abacus:render')))}
function render(screen='world'){if(!profile)return onboarding();({world,learn,lesson,levels,games,practice,result,levelup,assessment:assessmentQuestion,parent,locked,settings,brain}[screen]||world)()}
function onboarding(){app.innerHTML=`<div class="screen onboarding"><div class="ob-brand">🧮 <b>Abacus AI</b><small>My Abacus World</small></div>${babi('idle','hero')}<h1>Let's build your Abacus World!</h1><p class="ob-sub">Babi will learn how to help you.</p><div class="ob-card"><label>What's your name?</label><input id="childName" maxlength="18" autocomplete="off" placeholder="Your first name"><label>How old are you?</label><div class="age-grid"><button type="button" data-age="3-5">3–5</button><button type="button" data-age="6-8">6–8</button><button type="button" data-age="8-10">8–10</button><button type="button" data-age="10+">10+</button></div><label>Have you used an abacus before?</label><div class="experience"><button type="button" data-exp="new"><b>🌱 I'm new</b><small>Teach me from the beginning</small></button><button type="button" data-exp="known"><b>🚀 I know abacus</b><small>Give me a quick challenge</small></button></div><button type="button" class="primary" id="obNext" disabled>Enter My World →</button></div>${footer()}</div>`;let age='',exp='';document.querySelectorAll('[data-age]').forEach(b=>b.onclick=()=>{age=b.dataset.age;document.querySelectorAll('[data-age]').forEach(x=>x.classList.toggle('selected',x===b));ready()});document.querySelectorAll('[data-exp]').forEach(b=>b.onclick=()=>{exp=b.dataset.exp;document.querySelectorAll('[data-exp]').forEach(x=>x.classList.toggle('selected',x===b));ready()});$('#childName').oninput=ready;function ready(){$('#obNext').disabled=!($('#childName').value.trim()&&age&&exp)}$('#obNext').onclick=()=>{profile={name:$('#childName').value.trim(),age,experience:exp,createdAt:Date.now()};if(!saveProfile()){toast('Could not save your profile.');return}if(exp==='known'){assessmentIndex=0;assessmentScore=0;assessmentQuestion()}else render('world')}}
function ageCopy(){if(profile.age==='3-5')return {title:'Tiny Explorer',sub:'Short, playful bead adventures'};if(profile.age==='8-10')return {title:'Abacus Challenger',sub:'Accuracy, speed and smart moves'};if(profile.age==='10+')return {title:'Abacus Master Track',sub:'Challenge yourself and beat your best'};return {title:'Abacus Adventurer',sub:'Learn → practise → play → master'}}
function world(){const c=ageCopy();shell(`<section class="world-hero"><div class="world-babi">${babi('happy','small')}</div><div><p class="eyebrow">WELCOME BACK</p><h1>Hi ${esc(profile.name)}! 👋</h1><p>${c.title} · ${c.sub}</p></div></section><section class="mission"><span>🎯 TODAY'S MISSION</span><b>${state.streak?`Keep your ${state.streak}★ streak alive!`:'Start with your first bead lesson!'}</b><button id="missionBtn" type="button">Start →</button></section><div class="journey"><button id="learn" class="journey-card learn-card" type="button"><span>🌱</span><b>LEARN</b><small>Step-by-step bead lessons</small></button><button id="practice" class="journey-card practice-card" type="button"><span>🧮</span><b>PRACTISE</b><small>Build answers with beads</small></button><button id="games" class="journey-card play-card" type="button"><span>🎮</span><b>PLAY</b><small>Bead games & challenges</small></button><button id="levels" class="journey-card master-card" type="button"><span>🏆</span><b>MASTER</b><small>Levels 1–15</small></button></div><div class="bottom-row"><button class="soft" id="brain" type="button">🤖 Babi Brain</button><button class="soft" id="parent" type="button">👨‍👩‍👧 Parent Zone</button><button class="soft" id="settings" type="button">⚙ Settings</button></div>`,'world');$('#learn').onclick=()=>render('learn');$('#practice').onclick=()=>startLevel(state.currentLevel);$('#missionBtn').onclick=()=>state.currentLevel>6?render('locked'):startLevel(state.currentLevel);$('#games').onclick=()=>render('games');$('#levels').onclick=()=>render('levels');$('#brain').onclick=()=>render('brain');$('#parent').onclick=parentGate;$('#settings').onclick=()=>render('settings')}
const lessonData=[
  {title:'Meet your abacus',intro:'This is your abacus. The ONES rod is for single numbers. Each lower bead is worth 1.',task:'Make 1',target:1,why:'Move one lower bead toward the beam. One bead means one.'},
  {title:'Make 1, 2, 3, 4',intro:'Lower beads each count as one.',task:'Make 3',target:3,why:'Three lower beads together make 3.'},
  {title:'Meet the 5 bead',intro:'The upper bead is special. It is worth 5.',task:'Make 5',target:5,why:'Move the upper 5-bead toward the beam.'},
  {title:'Make 6, 7, 8, 9',intro:'Start with 5, then add lower beads.',task:'Make 8',target:8,why:'5 plus 3 lower beads makes 8.'},
  {title:'Tiny challenge',intro:'Now you choose the moves. Babi will check your beads.',task:'Make 4',target:4,why:'Use four lower beads.'}
];
function learn(){shell(`<div class="section-head">${babi('encourage','small')}<div><h1>Abacus Adventure</h1><p>Watch → try → check. Babi teaches one small idea at a time.</p></div></div><div class="lesson-list">${lessonData.map((x,i)=>`<button type="button" data-lesson="${i}"><b>${i+1}. ${x.title}</b><small>${x.intro}</small></button>`).join('')}<button type="button" data-lesson="5"><b>6. Ready for Level 1 ⭐</b><small>You know the basics. Let's practise.</small></button></div>`,'world');document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>lesson(Number(b.dataset.lesson)))}
function lesson(i){if(i===5){startLevel(1);return}const d=lessonData[i];let a=createAbacus(),done=false;const draw=()=>{const value=valueOf(a),good=value===d.target;done=good;const status=good?`<div class="lesson-success">🌟 Great! You made ${d.target}. ${d.why}</div>`:`<div class="lesson-guide"><b>👀 Watch:</b> ${d.why}</div>`;shell(`${babi(good?'celebrate':'encourage','medium')}<div class="lesson-card guided-lesson"><p class="eyebrow">ABACUS ADVENTURE · ${i+1}/6</p><h1>${d.title}</h1><p>${d.intro}</p><div class="lesson-task"><span>🎯 Your mission</span><b>${d.task}</b></div>${abacusHtml(a)}<div class="answer-card"><small>Your number</small><strong>${value}</strong></div>${status}<p class="hint">Tap a bead. Babi will show you what to do.</p><div class="actions"><button class="secondary" id="lessonBack" type="button">← Lessons</button><button class="primary" id="lessonCheck" type="button">${good?(i===4?'Finish lesson →':'Next lesson →'):'Check my beads ✓'}</button></div></div>`,'learn');bindAbacus(a,draw);$('#lessonBack').onclick=()=>render('learn');$('#lessonCheck').onclick=()=>{if(!done){toast(`Not quite. ${d.why}`);return}i===4?lesson(5):lesson(i+1)}};draw()}
function unlockedLevel(n){if(n<1||n>6)return false;if(n===1)return true;return !!state.levels[n-1]?.completed}
function levels(){const items=Array.from({length:15},(_,i)=>{const n=i+1,free=n<=6,open=free&&unlockedLevel(n),done=!!state.levels[n]?.completed;return `<button type="button" class="world-level ${!open?'locked':''} ${n===state.currentLevel?'current':''}" data-level="${n}" ${!open?'disabled':''}><span>${!free?'🔒':done?'✓':open?'★':'🔒'}</span><b>Level ${n}</b><small>${!free?'Premium':levelName(n)}</small></button>`}).join('');shell(`<div class="section-head"><div><h1>Master Path</h1><p>Level 1 starts open. Each next level unlocks after you master the previous one.</p></div></div><div class="world-levels">${items}</div><div class="premium-tease"><b>🔒 Levels 7–15 are waiting</b><small>Small friends · Big friends · Mixed mastery</small></div>`,'world');document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>startLevel(Number(b.dataset.level)))}
function levelName(n){if(n<=2)return 'Direct addition';if(n<=4)return 'Direct subtraction';if(n<=6)return 'Small friend addition';if(n<=8)return 'Small friend subtraction';if(n<=10)return 'Big friend addition';if(n<=12)return 'Big friend subtraction';return n===13?'Mixed direct + small':n===14?'Mixed small + big':'Full mixed mastery'}
function games(){shell(`<div class="section-head">${babi('happy','small')}<div><h1>Abacus Playroom 🎮</h1><p>Play with the same skills you learn.</p></div></div><div class="game-grid"><button id="builder" type="button"><span>🧱</span><b>Bead Builder</b><small>Build a number</small></button><button id="hunt" type="button"><span>🔎</span><b>Number Hunt</b><small>Spot the number</small></button><button id="speed" type="button"><span>⚡</span><b>Speed Challenge</b><small>Beat your best</small></button><button id="feed" type="button"><span>🍎</span><b>Feed Babi</b><small>Solve to feed Babi</small></button></div>`,'world');$('#builder').onclick=builder;$('#hunt').onclick=()=>startLevel(Math.min(state.currentLevel,6));$('#speed').onclick=()=>startLevel(Math.min(Math.max(state.currentLevel,2),6));$('#feed').onclick=()=>startLevel(Math.min(state.currentLevel,6))}
function builder(){let target=Math.floor(Math.random()*9)+1,a=createAbacus();const draw=()=>{shell(`${babi('encourage','small')}<div class="lesson-card"><p class="eyebrow">BEAD BUILDER</p><h1>Make ${target}</h1><p>Use the beads. No typing!</p>${abacusHtml(a)}<div class="answer-card"><small>Your number</small><strong>${valueOf(a)}</strong></div><button class="primary" id="builderCheck" type="button">Check →</button></div>`,'games');bindAbacus(a,draw);$('#builderCheck').onclick=()=>valueOf(a)===target?(state.streak++,save(),render('world')):toast(`Almost! ${target} needs a different bead move.`)};draw()}
function assessmentQuestion(){if(assessmentIndex>=5){const start=assessmentScore>=4?5:assessmentScore>=2?3:1;state.currentLevel=start;state.streak=0;save();render('world');toast(`Great! Babi found your starting Level ${start}.`);return}const examples=[[2,3],[5,4],[3,4],[7,2],[6,3]],pair=examples[assessmentIndex],ans=pair[0]+pair[1],a=createAbacus();const draw=()=>{shell(`${babi('encourage','small')}<div class="assessment"><p class="eyebrow">QUICK ABACUS CHECK · ${assessmentIndex+1}/5</p><h1>${pair[0]} + ${pair[1]} = ?</h1><p>Build the answer on the abacus.</p>${abacusHtml(a)}<div class="answer-card"><small>Your number</small><strong>${valueOf(a)}</strong></div><button class="primary" id="assessCheck" type="button">Check →</button></div>`,'world');bindAbacus(a,draw);$('#assessCheck').onclick=()=>{if(valueOf(a)===ans)assessmentScore++;assessmentIndex++;assessmentQuestion()}};draw()}
function startLevel(level){if(level>6||!unlockedLevel(level))return render('locked');state.currentLevel=level;state.streak=0;wrongCount=0;problem=generateProblem(level);childAbacus=createAbacus();save();render('practice')}
function practice(){const op=problem.operation==='add'?'+':'−';shell(`<div class="practice-meta"><span>LEVEL ${state.currentLevel} · ${levelName(state.currentLevel)}</span><span>${state.streak}/3 ⭐</span></div><div class="problem">${problem.operands[0]} ${op} ${problem.operands[1]} <span>= ?</span></div><p class="hint">Move the beads to make your answer.</p>${abacusHtml(childAbacus)}<div class="answer-card"><small>Your number</small><strong>${valueOf(childAbacus)}</strong></div><div class="actions"><button class="primary" id="check" type="button">Check ✓</button><button class="secondary" id="hint" type="button">💡 Babi Hint</button></div>`,'world');bindAbacus(childAbacus,()=>{practice()});$('#check').onclick=check;$('#hint').onclick=()=>toast(`Think about the ${problem.expectedRule} move.`)}
function bindAbacus(a,redraw){document.querySelectorAll('[data-upper]').forEach(b=>b.onclick=()=>{a.rods[+b.dataset.upper].upper=!a.rods[+b.dataset.upper].upper;redraw()});document.querySelectorAll('[data-lower]').forEach(b=>b.onclick=()=>{const r=+b.dataset.lower,i=+b.dataset.index,c=a.rods[r].lower;a.rods[r].lower=i<c?i:Math.min(4,i+1);redraw()})}
function check(){const {correct}=checkAnswer(problem,childAbacus),rule=problem.expectedRule;state.rules[rule]??={correct:0,wrong:0};state.levels[state.currentLevel]??={correct:0,wrong:0,completed:false};if(correct){state.rules[rule].correct++;state.levels[state.currentLevel].correct++;state.streak++;wrongCount=0;if(state.streak>=3){lastCompletedLevel=state.currentLevel;state.levels[lastCompletedLevel].completed=true;state.currentLevel=getNextLevel(lastCompletedLevel,state.streak,0);state.streak=0;save();if(lastCompletedLevel>=6)return render('locked');return render('levelup')}save();return render('result')}state.rules[rule].wrong++;state.levels[state.currentLevel].wrong++;wrongCount++;state.streak=0;if(wrongCount>=2){if(state.currentLevel>1)state.currentLevel=getNextLevel(state.currentLevel,0,wrongCount);wrongCount=0}save();render('result')}
function result(){const correct=valueOf(childAbacus)===problem.answer,op=problem.operation==='add'?'+':'−';shell(`${babi(correct?'happy':'encourage','medium')}<h1 class="result-title ${correct?'coral':''}">${correct?'Great job! 🌟':'Not yet — Babi believes in you!'}</h1><p class="result-sub">${correct?`You made ${problem.answer}. Streak ${state.streak}/3.`:`The answer is ${problem.answer}. Try the beads again.`}</p><div class="result-problem">${problem.operands[0]} ${op} ${problem.operands[1]} = <span>${problem.answer}</span></div><div class="actions"><button class="primary" id="next" type="button">${correct?'Next →':'Try Again'}</button><button class="secondary" id="hint" type="button">💡 Babi Hint</button></div>`,'world');$('#next').onclick=()=>{problem=generateProblem(Math.min(state.currentLevel,6));childAbacus=createAbacus();render('practice')};$('#hint').onclick=()=>toast(`This one uses the ${problem.expectedRule} idea. Watch the beads, then try again.`)}
function levelup(){const finished=lastCompletedLevel||Math.max(1,state.currentLevel-1);shell(`${babi('celebrate','medium')}<h1 class="levelup-title">Level Up! 🏆</h1><p class="result-sub">You mastered Level ${finished}!</p><div class="levelup-card"><b>${esc(profile.name)}</b>, your abacus brain is getting stronger.<br>Next adventure: Level ${state.currentLevel}.</div><div class="center"><button class="primary" id="continue" type="button">Continue →</button></div>`,'world');$('#continue').onclick=()=>startLevel(state.currentLevel)}
function locked(){shell(`${babi('encourage','medium')}<h1 class="result-title coral">One step at a time! 🔒</h1><div class="wall-card"><h2>Finish the current level first</h2><p>Master the open level and the next adventure unlocks.</p><strong>Levels 1–6 are the free path.</strong></div><button class="primary" id="stay" type="button">Back to My World</button>`,'world');$('#stay').onclick=()=>render('world')}
function brain(){shell(`${babi('happy','small')}<div class="brain-card"><p class="eyebrow">BABI BRAIN</p><h1>Ask Babi about abacus math</h1><p>Try: “How do I make 8?” or “What is 3 + 4?”</p><input id="brainInput" placeholder="Ask Babi…"><button class="primary" id="brainAsk" type="button">Ask Babi →</button><div id="brainReply" class="brain-reply">I only teach abacus and math. 🌟</div></div>`,'world');$('#brainAsk').onclick=()=>{const q=$('#brainInput').value.trim().toLowerCase(),nums=(q.match(/\d+/g)||[]).map(Number);let r='I can help with making numbers and simple abacus sums.';if(nums.length===1&&nums[0]>=0&&nums[0]<=99)r=`To make ${nums[0]}, use the 5 bead when needed, then the lower beads.`;else if(nums.length>=2&&(/\-|minus|subtract/.test(q))){const a=nums[0],b=nums[1];r=a>=b?`${a} − ${b} = ${a-b}. Build ${a}, then subtract ${b}.`:`Let's build ${a} first, then check the subtraction.`}else if(nums.length>=2&&(/\+|plus|add/.test(q))){const a=nums[0],b=nums[1];r=`${a} + ${b} = ${a+b}. Build ${a}, then add ${b}.`}$('#brainReply').textContent=r}}
function parentGate(){const answer=prompt('Parent check: 8 + 7 = ?');if(answer==='15')render('parent');else toast('That area is for grown-ups 😊')}
function parent(){const total=Object.values(state.rules).reduce((s,r)=>s+r.correct+r.wrong,0),correct=Object.values(state.rules).reduce((s,r)=>s+r.correct,0),accuracy=total?Math.round(correct/total*100):0;shell(`<div class="parent-card"><p class="eyebrow">PARENT ZONE</p><h1>${esc(profile.name)}'s Progress</h1><div class="stats"><div><b>${state.currentLevel}</b><small>Current level</small></div><div><b>${accuracy}%</b><small>Accuracy</small></div><div><b>${state.streak}</b><small>Streak</small></div></div><h3>Learning progress</h3><p>Direct: ${state.rules.direct.correct} correct · ${state.rules.direct.wrong} wrong</p><p>Small friend: ${state.rules.small.correct} correct · ${state.rules.small.wrong} wrong</p><p>Big friend: ${state.rules.big.correct} correct · ${state.rules.big.wrong} wrong</p></div>`,'world')}
function settings(){shell(`<div class="settings-card"><p class="eyebrow">SETTINGS</p><h1>My Abacus World</h1><p><b>${esc(profile.name)}</b> · age ${profile.age}</p><button class="secondary" id="reset" type="button">Start over with a new profile</button></div>`,'world');$('#reset').onclick=()=>{try{localStorage.removeItem(PROFILE_KEY);localStorage.removeItem(PROGRESS_KEY);localStorage.removeItem('abacus-ai-session-v1')}catch{}location.reload()}}
function abacusHtml(a){const rods=[0,1].map(r=>{const rod=a.rods[r],lowers=[0,1,2,3].map(i=>`<button type="button" class="bead lower ${i<rod.lower?'active':''}" data-lower="${r}" data-index="${i}" aria-label="${r?'Tens':'Ones'} lower bead ${i+1}"></button>`).join('');return `<div class="rod-column"><span class="rod-label">${r?'TENS':'ONES'}</span><div class="upper-zone"><button type="button" class="bead upper ${rod.upper?'active':''}" data-upper="${r}" aria-label="${r?'Tens':'Ones'} five bead"></button></div><div class="beam"></div><div class="lower-zone">${lowers}</div></div>`}).join('');return `<div class="abacus-wrap"><div class="abacus"><div class="abacus-inner">${rods}</div></div></div>`}
function toast(text){const old=$('.toast');old?.remove();const t=document.createElement('div');t.className='toast';t.textContent=text;document.body.appendChild(t);setTimeout(()=>t.remove(),2200)}
render();
