import {createAbacus,setValue,valueOf,generateProblem,getNextLevel,LEVEL_CONFIG} from './abacusEngine.js';

const KEY='abacus-ai-progress-v1';
const app=document.querySelector('#app');
let state=load();let problem=null;let childAbacus=createAbacus();let wrongCount=0;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{currentLevel:1,levels:{},rules:{direct:{correct:0,wrong:0},small:{correct:0,wrong:0},big:{correct:0,wrong:0}},streak:0};}catch{return {currentLevel:1,levels:{},rules:{direct:{correct:0,wrong:0},small:{correct:0,wrong:0},big:{correct:0,wrong:0}},streak:0};}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function nav(screen){render(screen);}
function render(screen='home'){if(screen==='welcome')return welcome();if(screen==='levels')return levels();if(screen==='practice')return practice();if(screen==='correct')return result(true);if(screen==='wrong')return result(false);if(screen==='levelup')return levelup();if(screen==='wall')return wall();return home();}
function shell(content){app.innerHTML=`<div class="screen"><div class="topbar"><span class="pill">🧮 Abacus Adventure</span><span class="pill">🔥 ${state.streak}</span></div><div class="card">${content}</div></div>`;}
function welcome(){shell(`<div class="mascot">🦊</div><h1 class="title">Abacus Adventure</h1><p class="subtitle">Learn numbers by moving beads, solving challenges, and earning badges!</p><div class="center" style="margin-top:28px"><button class="primary" id="start">Start Adventure 🚀</button></div>`);document.querySelector('#start').onclick=()=>nav('home');}
function home(){shell(`<div class="mascot">🦊</div><h2>Welcome back!</h2><p class="subtitle">You're on Level ${state.currentLevel}</p><div class="center" style="margin:24px 0"><button class="primary" id="play">▶ Play Level ${state.currentLevel}</button></div><div class="actions"><button class="secondary" id="levels">🗺️ Levels</button><button class="secondary" id="reset">Reset practice</button></div>`);document.querySelector('#play').onclick=()=>startLevel(state.currentLevel);document.querySelector('#levels').onclick=()=>nav('levels');document.querySelector('#reset').onclick=()=>{localStorage.removeItem(KEY);state=load();nav('home');};}
function levels(){const items=Array.from({length:15},(_,i)=>{const n=i+1,locked=n>6;return `<button class="level ${locked?'locked':''} ${n===state.currentLevel?'current':''}" data-level="${n}" ${locked?'disabled':''}>${locked?'🔒':'⭐'} Level ${n}</button>`}).join('');shell(`<h2 class="center">Level Map</h2><p class="subtitle">Levels 1–6 are free adventures.</p><div class="levels">${items}</div><div class="center" style="margin-top:22px"><button class="secondary" id="back">← Home</button></div>`);document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>startLevel(Number(b.dataset.level)));document.querySelector('#back').onclick=()=>nav('home');}
function startLevel(level){if(level>6)return nav('wall');state.currentLevel=level;wrongCount=0;problem=generateProblem(level);childAbacus=createAbacus();render('practice');}
function abacusHtml(){return `<div class="abacus"><div class="rod"><div class="beads"><button class="bead upper ${childAbacus.rods[0].upper?'active':''}" data-upper>5</button></div></div><div class="rod"><div class="beads">${[0,1,2,3].map(i=>`<button class="bead ${i<childAbacus.rods[0].lower?'active':''}" data-lower="${i}">1</button>`).join('')}</div></div></div>`;}
function practice(){shell(`<div class="pill">Level ${state.currentLevel} • ${problem.expectedRule} skill</div><div class="problem">${problem.operands[0]} ${problem.operation==='add'?'+':'−'} ${problem.operands[1]} = ?</div><p class="hint">Move the beads to make your answer.</p>${abacusHtml()}<div class="answer">Your beads: ${valueOf(childAbacus)}</div><div class="actions"><button class="primary" id="check">Check ✓</button><button class="secondary" id="hint">💡 Show a tutor hint</button></div>`);document.querySelector('[data-upper]').onclick=()=>{childAbacus.rods[0].upper=!childAbacus.rods[0].upper;render('practice');};document.querySelectorAll('[data-lower]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.lower);childAbacus.rods[0].lower=i<childAbacus.rods[0].lower?i:Math.min(4,i+1);render('practice');});document.querySelector('#check').onclick=check;document.querySelector('#hint').onclick=()=>alert(problem.expectedRule==='small'?'Try using a friend of 5.':'Think about how many beads you need.');}
function check(){const n=valueOf(childAbacus);const correct=n===problem.answer;const rule=problem.expectedRule;state.rules[rule]??={correct:0,wrong:0};if(correct){state.rules[rule].correct++;state.streak++;wrongCount=0;state.levels[state.currentLevel]??={correct:0,wrong:0};state.levels[state.currentLevel].correct++;save();if(state.streak>=3){if(state.currentLevel<15){state.currentLevel++;save();nav(state.currentLevel>6?'wall':'levelup');}else nav('levelup');}else nav('correct');}else{state.rules[rule].wrong++;wrongCount++;state.streak=0;state.levels[state.currentLevel]??={correct:0,wrong:0};state.levels[state.currentLevel].wrong++;if(wrongCount>=2&&state.currentLevel>1)state.currentLevel=getNextLevel(state.currentLevel,0,wrongCount);save();nav('wrong');}}
function result(correct){shell(`<div class="mascot ${correct?'celebrate':'shake'}">${correct?'🎉':'🦊'}</div><h2 class="center">${correct?'Great job!':'Almost!'}</h2><p class="subtitle center">${correct?`You made ${problem.answer}. Streak: ${state.streak}`:`Let’s try it again gently. The answer is ${problem.answer}.`}</p><div class="center" style="margin-top:24px"><button class="primary" id="next">${correct?'Next challenge':'Try again'}</button></div>`);document.querySelector('#next').onclick=()=>{problem=generateProblem(state.currentLevel);childAbacus=createAbacus();nav(state.currentLevel>6?'wall':'practice');};}
function levelup(){shell(`<div class="badge celebrate">🏆</div><h2 class="center">Level Up!</h2><p class="subtitle center">Amazing! You unlocked Level ${state.currentLevel}.</p><div class="center" style="margin-top:24px"><button class="primary" id="next">Continue</button></div>`);document.querySelector('#next').onclick=()=>startLevel(state.currentLevel);}
function wall(){shell(`<div class="mascot">🦊✨</div><h2 class="center">More adventures are waiting!</h2><p class="subtitle center">You completed the free Levels 1–6. Levels 7–15 are part of the next adventure.</p><div class="center" style="margin-top:24px"><button class="primary" id="home">Back to Home</button></div>`);document.querySelector('#home').onclick=()=>nav('home');}
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render('welcome');
