// Kid-first visual layer: playful, lightweight, offline-safe. No network assets.
(function(){
  const STYLE=`
    .kid-audio{display:inline-flex;align-items:center;gap:6px;min-height:40px;padding:7px 11px;border-radius:999px;background:#fff;border:2px solid rgba(107,66,38,.16);color:#4b2c18;font:900 13px ui-rounded,system-ui,sans-serif;box-shadow:0 3px 0 rgba(107,66,38,.14);touch-action:manipulation}.kid-audio:active{transform:scale(.96)}.kid-audio.speaking{box-shadow:0 0 0 4px rgba(255,177,55,.25),0 3px 0 rgba(107,66,38,.14)}
    .kid-music{display:inline-flex;align-items:center;gap:5px;min-height:40px;padding:7px 10px;border-radius:999px;background:#fff7dc;border:2px solid #e3bf67;color:#5b3b20;font:900 12px ui-rounded,system-ui,sans-serif;box-shadow:0 3px 0 rgba(107,66,38,.12)}.kid-music.on{background:#dff7df;border-color:#8cc68c}.kid-music:active{transform:scale(.96)}
    .world-screen{background:linear-gradient(180deg,#fffdf7 0%,#f7f1ff 55%,#eef9ff 100%)}
    .world-screen.kid-home{background:linear-gradient(180deg,#8fe2ff 0%,#dff8ff 22%,#fff4c9 48%,#dff5b8 100%);position:relative;overflow:hidden}.kid-home:before{content:'☁️   ☁️      ☀️       ☁️';position:absolute;left:0;right:0;top:58px;height:70px;text-align:center;font-size:31px;letter-spacing:16px;opacity:.75;pointer-events:none}.kid-home:after{content:'🌳   🌼   🦋   🌼   🌳';position:absolute;left:0;right:0;bottom:18px;text-align:center;font-size:24px;letter-spacing:4px;opacity:.8;pointer-events:none}
    .world-screen.kid-learn{background:linear-gradient(180deg,#effff1,#fffdf1 55%,#e9f8ff)}.world-screen.kid-play{background:linear-gradient(180deg,#f7efff,#fff7ea 58%,#eaf7ff)}.world-screen.kid-levels{background:linear-gradient(180deg,#fff7db,#fffaf1 52%,#eaf8ff)}.world-screen.kid-practice{background:linear-gradient(180deg,#eaf7ff,#fffdf4 52%,#eefbea)}.world-screen.kid-result{background:linear-gradient(180deg,#fff0f5,#fffbe8 55%,#eafaff)}.world-screen.kid-levelup{background:linear-gradient(180deg,#fff0bd,#fff7e7 50%,#f1eaff)}.world-screen.kid-locked{background:linear-gradient(180deg,#eef1f7,#fffaf0 55%,#f2ecff)}.world-screen.kid-settings{background:linear-gradient(180deg,#eefcff,#fffdf5 55%,#efffea)}.world-screen.kid-parent{background:linear-gradient(180deg,#fff5eb,#fffdf8 55%,#edf8ff)}.world-screen.kid-assessment{background:linear-gradient(180deg,#edf9ff,#fffbe9 55%,#f2edff)}.world-screen.kid-brain{background:linear-gradient(180deg,#f0edff,#fff9e9 55%,#eafff3)}
    .kid-home .content{position:relative;z-index:1}.kid-home .topbar{position:relative;z-index:2;background:rgba(255,255,255,.84);border-radius:20px;padding:5px 8px;box-shadow:0 5px 18px rgba(55,100,110,.12)}.kid-home .world-hero{background:linear-gradient(135deg,#fff,#fff3c9);border:3px solid #fff;box-shadow:0 8px 20px rgba(63,111,83,.16);position:relative}.kid-home .world-hero:after{content:'🧒 👧';position:absolute;right:15px;top:9px;font-size:25px;animation:kidFloat 2.2s ease-in-out infinite}.kid-home .mission{background:linear-gradient(135deg,#6a4228,#9b5b28);border:3px solid #f7d28d;box-shadow:0 6px 0 #4b2c18}.kid-home .journey-card{min-height:150px;border:3px solid rgba(255,255,255,.6);position:relative;overflow:hidden;box-shadow:0 7px 0 rgba(75,44,24,.25)}.kid-home .journey-card:before{content:'✦  ✧';position:absolute;right:10px;bottom:8px;font-size:20px;opacity:.55}.kid-home .journey-card:after{content:'';position:absolute;right:-18px;top:-18px;width:75px;height:75px;border-radius:50%;background:rgba(255,255,255,.14)}.kid-home .learn-card{background:linear-gradient(145deg,#49ad63,#247448)}.kid-home .practice-card{background:linear-gradient(145deg,#e6a13d,#a85e1d)}.kid-home .play-card{background:linear-gradient(145deg,#8c68d1,#60429b)}.kid-home .master-card{background:linear-gradient(145deg,#ffb84b,#9d5b20)}.kid-home .future-row{display:none}.kid-home .bottom-row{position:relative;z-index:3}.kid-home .soft{background:rgba(255,255,255,.82)}
    .kid-learn .lesson-list button{background:linear-gradient(135deg,#fff,#f3fff0);border-color:#b8dfb1;min-height:70px;transition:transform .15s ease}.kid-learn .lesson-list button:nth-child(2n){background:linear-gradient(135deg,#fff,#eef8ff);border-color:#b9dced}.kid-learn .lesson-list button:active,.kid-home .journey-card:active{transform:scale(.98)}
    .kid-play .game-grid button:nth-child(1){background:#fff5d9;border-color:#f2cf7a}.kid-play .game-grid button:nth-child(2){background:#eaf8ff;border-color:#a9d8ef}.kid-play .game-grid button:nth-child(3){background:#f4eaff;border-color:#cdb0eb}.kid-play .game-grid button:nth-child(4){background:#ecffe9;border-color:#b8dfaa}
    .kid-levels .world-level:not(.locked):nth-child(3n+1){background:linear-gradient(145deg,#54a85e,#277443)}.kid-levels .world-level:not(.locked):nth-child(3n+2){background:linear-gradient(145deg,#e69b31,#b96a18)}.kid-levels .world-level:not(.locked):nth-child(3n){background:linear-gradient(145deg,#8060c6,#5d3d99)}
    .kid-practice .problem{letter-spacing:1px;text-shadow:0 3px 0 rgba(255,255,255,.8)}.kid-practice .abacus-wrap{filter:drop-shadow(0 8px 12px rgba(57,90,110,.12))}.kid-result .result-problem{background:#fff;border-color:#f2b8c9}.kid-result .result-title{font-size:42px}.kid-levelup .levelup-title{text-shadow:0 3px 0 #fff}.kid-levelup .levelup-card{background:linear-gradient(135deg,#fff3bd,#f0e5ff);border:2px solid #e3bd55}
    .kid-page-stickers{display:flex;justify-content:center;gap:7px;margin:5px 0 2px;font-size:21px}.kid-page-stickers span{animation:kidFloat 2.4s ease-in-out infinite}.kid-page-stickers span:nth-child(2){animation-delay:.15s}.kid-page-stickers span:nth-child(3){animation-delay:.3s}.kid-page-stickers span:nth-child(4){animation-delay:.45s}.kid-page-stickers span:nth-child(5){animation-delay:.6s}.kid-page-stickers span:nth-child(6){animation-delay:.75s}@keyframes kidFloat{0%,100%{transform:translateY(0) rotate(-3deg)}50%{transform:translateY(-5px) rotate(3deg)}}
    .kid-home .journey-card span{font-size:38px}.kid-home .journey-card b{font-size:21px}.kid-home .world-hero h1{font-size:31px}.kid-home .mission b{font-size:18px}.kid-home .top-actions{display:flex;align-items:center;gap:5px}.kid-home .kid-audio,.kid-home .kid-music{min-height:34px;padding:5px 8px}
    @media(max-width:520px){.kid-audio{min-height:38px;padding:6px 9px;font-size:12px}.kid-music{min-height:38px;padding:6px 8px}.kid-home .journey-card{min-height:128px}.kid-home:before{top:52px;font-size:24px;letter-spacing:5px}.kid-home:after{font-size:20px}}
  `;
  function theme(screen){const text=(screen.innerText||'').toLowerCase();const c=[['kid-levelup',!!screen.querySelector('.levelup-title')],['kid-result',!!screen.querySelector('.result-title')],['kid-practice',!!screen.querySelector('.practice-meta')||!!screen.querySelector('.problem')],['kid-learn',text.includes('abacus adventure')||!!screen.querySelector('.lesson-list')],['kid-play',text.includes('playroom')||!!screen.querySelector('.game-grid')],['kid-levels',text.includes('master path')||!!screen.querySelector('.world-levels')],['kid-locked',!!screen.querySelector('.wall-card')],['kid-settings',!!screen.querySelector('.settings-card')],['kid-parent',!!screen.querySelector('.parent-card')],['kid-assessment',!!screen.querySelector('.assessment')],['kid-brain',!!screen.querySelector('.brain-card')]];c.forEach(([k,on])=>screen.classList.toggle(k,on));if(!c.some(x=>x[1]))screen.classList.add('kid-home')}
  function audio(screen){const actions=screen.querySelector('.top-actions');if(!actions||actions.querySelector('.kid-audio'))return;const b=document.createElement('button');b.className='kid-audio';b.type='button';b.innerHTML='🔊 <span>Babi</span>';b.setAttribute('aria-label','Tap Babi to hear this page');b.onclick=()=>{const v=window.BabiVoice;if(!v?.context)return;const [en,ta]=v.context();b.classList.add('speaking');v.say(en,ta);setTimeout(()=>b.classList.remove('speaking'),4200)};actions.prepend(b)}
  function music(screen){const actions=screen.querySelector('.top-actions');if(!actions||actions.querySelector('.kid-music')||!window.AbacusAudio)return;const b=document.createElement('button');b.className='kid-music';b.type='button';b.textContent=window.AbacusAudio.isMusicOn()?'🎵 On':'🎵 Music';b.setAttribute('aria-label','Turn gentle music on or off');b.onclick=()=>{const on=window.AbacusAudio.musicToggle();b.classList.toggle('on',on);b.textContent=on?'🎵 On':'🎵 Music'};actions.appendChild(b)}
  function decorate(){const screen=document.querySelector('.world-screen');if(!screen)return;theme(screen);audio(screen);music(screen);if(!screen.querySelector('.kid-page-stickers')){const main=screen.querySelector('.content');if(main){const s=document.createElement('div');s.className='kid-page-stickers';s.innerHTML='<span>🧒</span><span>👧</span><span>⭐</span><span>🌈</span><span>🧮</span><span>💛</span>';main.prepend(s)}}}
  function inject(){if(!document.getElementById('kid-ui-style')){const s=document.createElement('style');s.id='kid-ui-style';s.textContent=STYLE;document.head.appendChild(s)}decorate()}
  const afterRender=()=>queueMicrotask(inject);
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
  // Navigation is click-driven in the core app, so decorate after the click instead of
  // watching the whole document with a MutationObserver.
  document.addEventListener('click',afterRender,{passive:true});
})();
