import {createAbacus,valueOf,setValue,generateProblem,checkAnswer} from './abacusEngine.js';

const KEY='abacus-ai-play-v1';
const $=s=>document.querySelector(s);
const app=$('#app');
let playState=load();
let raceTimer=null;

function load(){try{return JSON.parse(localStorage.getItem(KEY))||{raceBest:0,memoryBest:0,mysteryBest:0}}catch{return {raceBest:0,memoryBest:0,mysteryBest:0}}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(playState))}catch{}}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function babi(){return `<svg class="babi play-babi" viewBox="0 0 160 160" aria-label="Babi"><use href="./assets/mascot/babi.svg#happy"></use></svg>`}
function shell(content){clearInterval(raceTimer);app.innerHTML=`<div class="screen world-screen"><header class="topbar"><button class="icon-btn" id="playBack">←</button><div class="brand"><span class="brand-mark">🧮</span><span><strong>Abacus AI</strong><small>Playroom</small></span></div></header><main class="content">${content}</main><div class="footer">Powered by PromptStudioAI<br><small>promptstudioai.in</small></div></div>`;$('#playBack').onclick=()=>window.__abacusRender?.('world')||location.reload()}
function renderPlay(){shell(`<div class="section-head">${babi()}<div><p class="eyebrow">BABI'S PLAYROOM</p><h1>Pick a game! 🎮</h1><p>Play with the same abacus skills you learn.</p></div></div><div class="play-mode-grid"><button data-mode="race"><span>🏁</span><b>Bead Race</b><small>Solve before time runs out</small><em>Best: ${playState.raceBest}</em></button><button data-mode="memory"><span>🧠</span><b>Memory Match</b><small>Match numbers to bead patterns</small><em>Best: ${playState.memoryBest}</em></button><button data-mode="mystery"><span>🔮</span><b>Mystery Number</b><small>Read Babi's beads</small><em>Best: ${playState.mysteryBest}</em></button></div>`);document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>({race:beadRace,memory:memoryMatch,mystery:mysteryNumber}[b.dataset.mode])())}
function abacus(a,cls=''){const rods=[0,1].map(r=>{const d=a.rods[r],low=[0,1,2,3].map(i=>`<button class="bead lower ${i<d.lower?'active':''}" data-r="${r}" data-i="${i}" type="button"></button>`).join('');return `<div class="rod-column"><span class="rod-label">${r?'TENS':'ONES'}</span><div class="upper-zone"><button type="button" class="bead upper ${d.upper?'active':''}" data-u="${r}"></button></div><div class="beam"></div><div class="lower-zone">${low}</div></div>`}).join('');return `<div class="abacus-wrap ${cls}"><div class="abacus"><div class="abacus-inner">${rods}</div></div></div>`}
function bind(a,draw){document.querySelectorAll('[data-u]').forEach(b=>b.onclick=()=>{a.rods[+b.dataset.u].upper=!a.rods[+b.dataset.u].upper;draw()});document.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{const r=+b.dataset.r,i=+b.dataset.i,c=a.rods[r].lower;a.rods[r].lower=i<c?i:Math.min(4,i+1);draw()})}
function beadRace(){let score=0,time=30,problem=generateProblem(1),a=createAbacus(),running=true;const draw=()=>{shell(`<div class="game-head"><span>🏁 BEAD RACE</span><strong id="raceTime">${time}s</strong><b id="raceScore">⭐ ${score}</b></div><div class="whoosh" id="whoosh">🧮</div><div class="problem">${problem.operands[0]} ${problem.operation==='add'?'+':'−'} ${problem.operands[1]} = ?</div>${abacus(a)}<div class="answer-card">Your number: <strong id="raceValue">${valueOf(a)}</strong></div><button class="primary" id="raceCheck">Check ✓</button><p id="raceMsg">Go, go, go!</p>`);bind(a,()=>{draw();$('#whoosh')?.classList.add('whoosh-in')});$('#raceCheck').onclick=()=>{if(!running)return;if(checkAnswer(problem,a).correct){score++;window.abacusSound?.correct?.();problem=generateProblem(Math.min(6,Math.max(1,1+Math.floor(score/3))));a=createAbacus();draw()}else{window.abacusSound?.wrong?.();$('#raceMsg').textContent='Almost! Try the beads again 💛'}}};draw();raceTimer=setInterval(()=>{time--;const el=$('#raceTime');if(el)el.textContent=time+'s';if(time<=0){running=false;clearInterval(raceTimer);if(score>playState.raceBest)playState.raceBest=score;save();$('#raceCheck').disabled=true;$('#raceMsg').textContent=`Time! You solved ${score} ${score===1?'problem':'problems'}! 🎉`;window.abacusSound?.cheer?.()}},1000)}
function pattern(n){const a=createAbacus();setValue(a,n);return JSON.stringify(a.rods)}
function memoryMatch(){const nums=[1,2,3,5,6,8];const cards=nums.flatMap(n=>[{id:`n${n}`,pair:n,type:'number',label:String(n)},{id:`p${n}`,pair:n,type:'pattern',label:pattern(n)}]).sort(()=>Math.random()-.5);let open=[],matched=0,moves=0;const draw=()=>{shell(`<div class="game-head"><span>🧠 MEMORY MATCH</span><b>Pairs ${matched}/${nums.length}</b><b>Moves ${moves}</b></div><p class="center">Find the number that matches Babi's bead pattern.</p><div class="memory-grid">${cards.map(c=>`<button class="memory-card ${open.includes(c.id)?'open':''} ${matchedCards().includes(c.pair)?'matched':''}" data-card="${c.id}">${open.includes(c.id)||matchedCards().includes(c.pair)?(c.type==='number'?esc(c.label):miniPattern(c.label)):'?'}</button>`).join('')}</div><p class="center" id="memoryMsg">Tap two cards.</p>`,'world');document.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>flip(b.dataset.card))};const matchedCards=()=>cards.filter(c=>c.matched).map(c=>c.pair);const flip=id=>{if(open.includes(id)||open.length>=2)return;const c=cards.find(x=>x.id===id);if(!c||c.matched)return;open.push(id);draw();if(open.length===2){moves++;const [a,b]=open.map(x=>cards.find(c=>c.id===x));if(a.pair===b.pair&&a.type!==b.type){a.matched=b.matched=true;open=[];window.abacusSound?.correct?.();if(matchedCards().length===nums.length){playState.memoryBest=playState.memoryBest?Math.min(playState.memoryBest,moves):moves;save();setTimeout(()=>shell(`${babi()}<div class="lesson-card"><h1>Memory Master! 🧠🏆</h1><p>You matched every bead pattern.</p><h2>${moves} moves</h2><button class="primary" id="memoryDone">Play again →</button></div>`,'world'),400)}}else{window.abacusSound?.wrong?.();setTimeout(()=>{open=[];draw()},650)}}};draw()}
function miniPattern(serialized){let rods;try{rods=JSON.parse(serialized)}catch{return '🧮'}return `<span class="mini-pattern">${rods.map(r=>`${r.upper?'●':'○'}${'●'.repeat(r.lower)}${'○'.repeat(4-r.lower)}`).join(' | ')}</span>`}
function mysteryNumber(){let target=Math.floor(Math.random()*9)+1,score=0;const draw=()=>{const a=createAbacus();setValue(a,target);const options=[target];while(options.length<4){const n=Math.floor(Math.random()*9)+1;if(!options.includes(n))options.push(n)}options.sort(()=>Math.random()-.5);shell(`<div class="game-head"><span>🔮 MYSTERY NUMBER</span><b>⭐ ${score}</b></div>${babi()}<h1 class="center">What number is Babi showing?</h1>${abacus(a,'mystery-abacus')}<div class="choice-grid">${options.map(n=>`<button data-choice="${n}">${n}</button>`).join('')}</div><p class="center" id="mysteryMsg">Look carefully at the beads 👀</p>`);document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const n=+b.dataset.choice;if(n===target){score++;window.abacusSound?.correct?.();target=Math.floor(Math.random()*9)+1;draw()}else{window.abacusSound?.wrong?.();$('#mysteryMsg').textContent='Not that one — count the beads again! 💛'}})};draw()}
window.__abacusPlay=renderPlay;
window.addEventListener('beforeunload',()=>clearInterval(raceTimer));
