// Lightweight 10-problem session recap. Offline/local only.
(function(){
  const KEY='abacus-ai-session-v1',TOTAL=10;
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')||{total:0,correct:0,startedAt:Date.now()}}catch{return {total:0,correct:0,startedAt:Date.now()}}};
  const write=s=>{try{localStorage.setItem(KEY,JSON.stringify(s))}catch{}};
  let session=read(),shown=false;
  function reset(){session={total:0,correct:0,startedAt:Date.now()};write(session);shown=false}
  function style(){if(document.getElementById('session-summary-style'))return;const s=document.createElement('style');s.id='session-summary-style';s.textContent=`.session-meter{display:block;margin:0;padding:8px 12px;border-radius:12px;background:#fff8dc;border:2px solid rgba(107,66,38,.1);font:900 13px ui-rounded,system-ui,sans-serif;color:#4b2c18;text-align:center}.session-meter b{font-size:15px}.session-overlay{position:fixed;inset:0;z-index:10000;display:grid;place-items:center;padding:18px;background:rgba(40,24,12,.38)}.session-card{width:min(520px,100%);padding:24px 20px;border-radius:28px;background:#fffdf7;border:3px solid #f1c46b;box-shadow:0 18px 60px rgba(40,24,12,.25);text-align:center;color:#4b2c18}.session-card .emoji{font-size:54px}.session-card h1{margin:6px 0;font-size:30px}.session-score{font-size:23px;font-weight:950;margin:12px 0}.session-next{margin:8px 0 18px;padding:12px 14px;border-radius:16px;background:#fff3c9;font-weight:800;line-height:1.4}.session-card button{min-width:210px}`;document.head.appendChild(s)}
  function meter(){const host=document.querySelector('.practice-meta');if(!host)return;let m=host.querySelector(':scope > .session-meter');if(!m){m=document.createElement('div');m.className='session-meter';host.appendChild(m)}m.innerHTML=`🎯 Session <b>${Math.min(session.total+1,TOTAL)}/${TOTAL}</b>`}
  function state(){try{return JSON.parse(localStorage.getItem('abacus-ai-progress-v2')||'null')||{currentLevel:1,streak:0}}catch{return {currentLevel:1,streak:0}}}
  function show(){if(shown)return;shown=true;style();const p=state(),next=Math.max(0,3-Number(p.streak||0)),nextText=p.currentLevel>=6?'Keep practising — you have reached the free path limit.':next===0?`Level ${Number(p.currentLevel||1)+1} is ready!`:`Next level unlocks in ${next} more ${next===1?'win':'wins'}.`;const el=document.createElement('div');el.className='session-overlay';el.innerHTML=`<section class="session-card" role="dialog" aria-modal="true"><div class="emoji">🎉</div><h1>Great session!</h1><div class="session-score">You solved ${session.correct}/${TOTAL} problems!</div><div class="session-next">${nextText}</div><button type="button" class="primary" id="sessionContinue">Keep Practising →</button></section>`;document.body.appendChild(el);el.querySelector('#sessionContinue').onclick=()=>{el.remove();reset();meter()}}
  function parsePractice(){const problem=document.querySelector('.problem')?.textContent||'';const m=problem.match(/(\d+)\s*([+−-])\s*(\d+)/);const ans=Number(document.querySelector('.answer-card strong')?.textContent||NaN);if(!m||!Number.isFinite(ans))return null;const expected=m[2]==='+'?Number(m[1])+Number(m[3]):Number(m[1])-Number(m[3]);return {correct:ans===expected}}
  function parseBuilder(){const text=document.querySelector('.lesson-card h1')?.textContent||'';const m=text.match(/Make\s+(\d+)/i);const ans=Number(document.querySelector('.answer-card strong')?.textContent||NaN);if(!m||!Number.isFinite(ans))return null;return {correct:ans===Number(m[1])}}
  function record(r){if(!r||session.total>=TOTAL)return;session.total++;if(r.correct)session.correct++;write(session);meter();if(session.total>=TOTAL)setTimeout(show,180)}
  function handleClick(e){const target=e.target?.closest?.('#check,#builderCheck');if(!target)return;const r=target.id==='builderCheck'?parseBuilder():parsePractice();record(r)}
  style();
  document.addEventListener('click',handleClick,{capture:true,passive:true});
  window.addEventListener('abacus:render',meter);
})();
