/* V1 Progress Passport — local-only, presentation-only.
   Uses the authoritative progress record; owns no learning state and never sends data.
   Inspired by the PromptStudioAI reference pattern: explicit states, bounded output,
   graceful failure, and a thin adapter around the existing product core.
*/
(function(){
  const app=document.getElementById('app');if(!app)return;
  const read=()=>{try{return JSON.parse(localStorage.getItem('abacus-ai-progress-v2')||'null')}catch{return null}};
  const pct=(a,b)=>b?Math.round((a/b)*100):0;
  let last=null;
  function style(){if(document.getElementById('v1-progress-style'))return;const s=document.createElement('style');s.id='v1-progress-style';s.textContent=`
    .v1-passport{margin:12px 0;padding:14px 15px;border-radius:19px;background:#fffdf7;border:2px solid #d8c09a;box-shadow:0 7px 18px rgba(75,44,24,.09);color:#4b2c18}.v1-passport-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.v1-passport-head b{font-size:15px}.v1-passport-head span{font-size:11px;font-weight:900;color:#8b6a49}.v1-passport-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:10px}.v1-passport-stat{padding:9px 6px;border-radius:13px;background:#f6e8cf;text-align:center}.v1-passport-stat strong{display:block;font-size:21px;color:#6b4226}.v1-passport-stat small{display:block;font-size:9px;color:#75685d;font-weight:800;margin-top:2px}.v1-passport-bar{height:7px;margin-top:10px;background:#eadbc2;border-radius:99px;overflow:hidden}.v1-passport-bar i{display:block;height:100%;width:0;background:#c98a3e;border-radius:inherit;transition:width .3s ease}.v1-passport-note{margin:8px 0 0;font-size:11px;color:#75685d;line-height:1.35}.v1-rule{display:inline-block;margin-top:6px;padding:5px 8px;border-radius:999px;background:#fff4d9;border:1px solid #e2c89a;font-size:10px;font-weight:900;color:#6b4226}
    @media(max-width:520px){.v1-passport-grid{gap:5px}.v1-passport-stat{padding:8px 3px}}
  `;document.head.appendChild(s)}
  function metrics(){const p=read()||{},levels=p.levels||{},rules=p.rules||{};let done=0,totalCorrect=0,totalWrong=0,bestRule='';Object.keys(levels).forEach(k=>{if(levels[k]?.completed)done++;totalCorrect+=Number(levels[k]?.correct||0);totalWrong+=Number(levels[k]?.wrong||0)});const totals={};Object.entries(rules).forEach(([name,v])=>{const c=Number(v?.correct||0),w=Number(v?.wrong||0);totals[name]={c,w,rate:pct(c,c+w)};if(!bestRule||totals[name].rate>totals[bestRule].rate)bestRule=name});const attempts=totalCorrect+totalWrong,accuracy=pct(totalCorrect,attempts),level=Math.min(6,Math.max(1,Number(p.currentLevel)||1));return {level,done,accuracy,sessions:Number(p.sessions)||0,bestRule:totals[bestRule]?.c?bestRule:null,practice:!!p.practiceCompleted,learn:!!p.learn?.completed}};
  function render(){const hero=document.querySelector('.world-hero');if(!hero)return;const m=metrics();if(last&&last.hero===hero&&last.level===m.level&&last.done===m.done&&last.accuracy===m.accuracy&&last.sessions===m.sessions&&last.practice===m.practice)return;last={hero,...m};document.querySelector('.v1-passport')?.remove();const el=document.createElement('section');el.className='v1-passport';const progress=Math.min(100,Math.round((Math.max(0,m.level-1)/5)*100));const focus=m.bestRule?`Your strongest recent skill: ${m.bestRule==='direct'?'direct moves':m.bestRule==='small'?'small friends':m.bestRule==='big'?'big friends':'mixed practice'}.`:'Your first practice will start building your progress picture.';el.innerHTML=`<div class="v1-passport-head"><b>🧭 Your Abacus Passport</b><span>${m.learn?'Learn ✓':'Learn first'}</span></div><div class="v1-passport-grid"><div class="v1-passport-stat"><strong>L${m.level}</strong><small>CURRENT LEVEL</small></div><div class="v1-passport-stat"><strong>${m.accuracy}%</strong><small>ACCURACY</small></div><div class="v1-passport-stat"><strong>${m.sessions}</strong><small>SESSIONS</small></div></div><div class="v1-passport-bar"><i style="width:${progress}%"></i></div><p class="v1-passport-note">${focus} ${m.practice?'Keep building one level at a time.':'Complete Learn, then Practice unlocks.'}</p>${m.done?`<span class="v1-rule">⭐ ${m.done} level${m.done===1?'':'s'} completed</span>`:''}</section>`;hero.insertAdjacentElement('afterend',el)}
  style();const observer=new MutationObserver(()=>{requestAnimationFrame(render)});observer.observe(app,{childList:true,subtree:true});render();
})();
